[build]
  command = "npx expo export -p web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  EXPO_NO_TELEMETRY = "1"

# SPA: manda tutto a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers (CSP compatibile con Firebase/Google OAuth e Expo web)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://www.gstatic.com https://www.googletagmanager.com https://www.googleapis.com https://accounts.google.com; connect-src 'self' https://*.googleapis.com https://*.gstatic.com https://*.firebaseio.com https://*.firebaseapp.com https://accounts.google.com; img-src 'self' data: blob: https://*.gstatic.com https://*.googleusercontent.com https://developers.google.com; style-src 'self' 'unsafe-inline'; frame-src https://accounts.google.com https://*.firebaseapp.com https://*.web.app;"
